spring:
  application:
    name: server-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/RodrigoMaliachi/sistema-academia
          default-label: local
          search-paths: config-data

server:
  port: 5051